### ISSUE TITLE
TypeError: VaeImageProcessor.preprocess() got an unexpected keyword argument 'crops_coords'

### ISSUE THREAD

**Issue by zhenyuanzhou** [AIFSH/IMAGDressing-ComfyUI#3]
got prompt
====================== pipe load finish ===================
100%|████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  2.99it/s]
100%|████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  3.44it/s]
!!! Exception during processing!!! VaeImageProcessor.preprocess() got an unexpected keyword argument 'crops_coords'
Traceback (most recent call last):
  File "F:\ComfyUI-master\execution.py", line 152, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "F:\ComfyUI-master\execution.py", line 82, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "F:\ComfyUI-master\execution.py", line 75, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "F:\ComfyUI-master\custom_nodes\IMAGDressing-ComfyUI\__init__.py", line 508, in generate
    output = self.pipe(
  File "f:\py310ai\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "F:\ComfyUI-master\custom_nodes\IMAGDressing-ComfyUI\imagdressing\dressing_sd\pipelines\IMAGDressing_v1_pipeline_controlnet_inpainting.py", line 264, in __call__
    control_image = self.prepare_control_image(
  File "F:\ComfyUI-master\custom_nodes\IMAGDressing-ComfyUI\imagdressing\dressing_sd\pipelines\IMAGDressing_v1_pipeline_controlnet_inpainting.py", line 95, in prepare_control_image
    image = self.control_image_processor.preprocess(
TypeError: VaeImageProcessor.preprocess() got an unexpected keyword argument 'crops_coords'

Prompt executed in 5.12 seconds

**Comment by AIFSH** [comment]
update diffusers
