### ISSUE TITLE
Cannot import E:\FreeSoft\sd\comfyui-aki-v1.3\custom_nodes\IMAGDressing-ComfyUI module for custom nodes: No module named 'utils.transforms'; 'utils' is not a package

### ISSUE THREAD

**Issue by water110** [AIFSH/IMAGDressing-ComfyUI#4]
Traceback (most recent call last):
  File "E:\FreeSoft\sd\comfyui-aki-v1.3\nodes.py", line 1931, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "E:\FreeSoft\sd\comfyui-aki-v1.3\custom_nodes\IMAGDressing-ComfyUI\__init__.py", line 33, in <module>
    from imagdressing.preprocess.humanparsing.run_parsing import Parsing
  File "E:\FreeSoft\sd\comfyui-aki-v1.3\custom_nodes\IMAGDressing-ComfyUI\imagdressing\preprocess\humanparsing\run_parsing.py", line 10, in <module>
    from parsing_api import onnx_inference
  File "E:\FreeSoft\sd\comfyui-aki-v1.3\custom_nodes\IMAGDressing-ComfyUI\imagdressing\preprocess\humanparsing\parsing_api.py", line 13, in <module>
    from datasets.simple_extractor_dataset import SimpleFolderDataset
  File "E:\FreeSoft\sd\comfyui-aki-v1.3\custom_nodes\IMAGDressing-ComfyUI\imagdressing\preprocess\humanparsing\datasets\simple_extractor_dataset.py", line 21, in <module>
    from utils.transforms import get_affine_transform
ModuleNotFoundError: No module named 'utils.transforms'; 'utils' is not a package

Cannot import E:\FreeSoft\sd\comfyui-aki-v1.3\custom_nodes\IMAGDressing-ComfyUI module for custom nodes: No module named 'utils.transforms'; 'utils' is not a package

**Comment by sunkinux** [comment]
same problem

**Comment by JohnBaffin** [comment]
![捕获](https://github.com/user-attachments/assets/13c3f5b2-9837-440b-b13d-56b9b19a6baf)

like thsi?

**Comment by Ethanyxy** [comment]
same problem
