### ISSUE TITLE
error

### ISSUE THREAD

**Issue by YacratesWyh** [AIFSH/IMAGDressing-ComfyUI#7]
!!! Exception during processing!!! 'NoneType' object is not callable
Traceback (most recent call last):
  File "/home/admin188/AI/ComfyUI2/ComfyUI/execution.py", line 154, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/admin188/AI/ComfyUI2/ComfyUI/execution.py", line 84, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/admin188/AI/ComfyUI2/ComfyUI/execution.py", line 77, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/admin188/AI/ComfyUI2/ComfyUI/custom_nodes/IMAGDressing-ComfyUI/__init__.py", line 423, in generate
    output = self.pipe(
             ^^^^^^^^^^
TypeError: 'NoneType' object is not callable

**Comment by YacratesWyh** [comment]
weird for It's  fine after a reinstall. Maybe because I manually move to the /pretrained_model/IMAGDressing/sd as it's not exist in the auto process.

**Comment by saipranathi7** [comment]
Hey I got the same error , how did you get it right ?
